name: go unit tests

on:
  push:
    paths: 
      - '**.go'
  pull_request:


env:
  GO_MOD_DIR: ${{ github.workspace }}/cert-generator/


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build src binaries
        run: | 
          cd ${{ env.GO_MOD_DIR }}
          go build cmd/tls.go 