name: go unit tests

on:
  push:
  pull_request:


env:
  GO_MOD_DIR: ${{ github.workspace }}/src/cert-generator
  GO_TEST_DIR: ${{ github.workspace }}/src/cert-generator/tests/pkg


jobs:
  fetch:
    runs-on: [self-hosted , build]
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4

  build:
    needs: fetch
    runs-on: [self-hosted , build]
    steps:
      - name: build src binaries
        run: | 
          cd ${{ env.GO_MOD_DIR }}
          go build cmd/tls.go

  unit-tests:
      needs: fetch
      runs-on: [self-hosted , build]
      steps:
        - name: run unit tests
          run: | 
            cd ${{ env.GO_TEST_DIR }}
            export PATH=$PATH:/usr/local/go/bin
            go test ./*
